### PR TITLE
Sauce

### PR DESCRIPTION
**Pull request by stdavis**
Chrome on windows is failing for some reason. Looks like it's trying to get the test results before the test suite is finished. Spent a bit on it but don't have time to figure it out. But at least sauce is wired up and working.

### CODE REVIEW

**Comment by stdavis** [comment]
@steveoh Want to review this?

**Comment by stdavis** [comment]
Maybe we should just leave this open until we can get the tests passing on all platforms.

**Comment by steveoh** [comment]
are you feeling better about the tests passing now?

**Comment by stdavis** [comment]
Yes.

**Pull request merged**
